#ifndef UI_FSM_APP_H
#define UI_FSM_APP_H
#include <stdint.h>
#include <stdbool.h>

typedef enum{
    STATE_UI_INIT,
    STATE_UI_IDLE,
    STATE_UI_INPUT,
    STATE_UI_VERIFY,
    STATE_UI_DENY,
    STATE_UI_MENU,
    STATE_UI_UNLOCK,
    STATE_UI_LOCK,
    STATE_UI_ENTER_NEW,
    STATE_UI_CONFIRM_NEW,
    STATE_UI_SAVE,
    STATE_UI_WAIT_UID,
    STATE_UI_VERIFY_UID,
    STATE_UI_DUPLICATE,
    STATE_UI_SAVE_UID,
    STATE_UI_SUCCESS,
}UIState;

typedef enum{
    EVENT_UI_USER_ACTION,
    EVENT_UI_SUBMIT_PIN_UID,
    EVENT_UI_RETRY,
    EVENT_UI_WRONG,
    EVENT_UI_CORRECT,
    EVENT_UI_UNLOCK_DOOR,
    EVENT_UI_DOOR_CLOSED,
    EVENT_UI_CHANGE_PASSWORD,
    EVENT_UI_CANCEL,
    EVENT_UI_MISMATCH,
    EVENT_UI_MATCH,
    EVENT_UI_ENROLL_UID,
    EVENT_UI_UID_DETECTED,
    EVENT_UI_UID_EXISTS,
    EVENT_UI_VALID,
    EVENT_UI_NOT_EXISTS,
    EVENT_UI_EXIT
}UIEvent;

void UIFSM_Init(void);
void UIFSM_Process(void);
UIState UIFSM_getState(void);

#endif // UI_FSM_APP_H